### ISSUE TITLE
[1.12.2] Unable to start server

### ISSUE THREAD

**Issue by Twilix01** [jodlodi/TwilightTweaks#3]
Server crashes while starting up with this mod installed. 

Crash report: https://pastebin.com/UUQSMedU

**Comment by jodlodi** [comment]
Could you post the "latest.log" that comes from this crash as well?

**Comment by Twilix01** [comment]
Sure thing! Here it is.

https://pastebin.com/t2SQFNWP

**Comment by jodlodi** [comment]
Apologizes for the several month wait, the issue is fixed now
